Adx 961 verify that localization works with new validation framework
fjelltopp/ckanext-validation pull request #100
Opened 2023-07-13 13:06 UTC by A-Souhei

## Description

Added translations (FR, PT) for validations,
added webassets folder for babel to check for texts to be translated,
edited resource.config to reflect frictionless-components

## Checklist

Put an `x` in the boxes that apply to this pull request (you can also fill these out after opening the pull request).
You may not need to check all boxes.

- [ ] The Jira ticket for this issue has been updated to "Ready to Review" or equivalent.
- [ ] I have developed these changes in discussion with the appropriate project manager.
- [ ] My code follows the general Fjelltopp documentation (see Confluence).
- [ ] I have made corresponding changes to the Fjelltopp documentation (see Confluence).
- [ ] I have rebased this branch with master.
- [ ] New dependency changes have been committed.
- [ ] I have added automated tests that prove my fix is effective or that my feature works.
- [ ] New and existing tests pass locally with my changes.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own code.
- [ ] I have assigned at least one reviewer.

2023-07-17 06:16 UTC, tomeksabala requested changes, later dismissed

2023-07-17 06:16 UTC, tomeksabala commented on ckanext/validation/i18n/fr/LC_MESSAGES/ckanext-validation.po
> +"Generated-By: Babel 2.7.0\n"
Please update the metadata to Fjelltopp, Toavina, info@fjelltopp.org

2023-07-19 13:09 UTC, ChasNelson1990 requested changes
Just a wee change or two please

2023-07-19 13:09 UTC, ChasNelson1990 commented on ckanext/validation/i18n/fr/LC_MESSAGES/ckanext-validation.po
> +"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
@A-Souhei, can you put you here?

2023-07-19 13:09 UTC, ChasNelson1990 commented on ckanext/validation/i18n/pt_PT/LC_MESSAGES/ckanext-validation.po
> +"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
And here?

2023-07-21 12:40 UTC, ChasNelson1990 approved these changes

2023-07-26 14:29 UTC, merged