ADX-521 Ammend custom constraints check
fjelltopp/ckanext-validation pull request #48
Opened 2020-11-25 13:19 UTC by jonathansberry

This PR copies the existing custom-constraint check from goodtables-py and ammends it's behaviour slightly. 

A custom constraint is a simple expression to be evaluated to a boolean, using the column headings of the data table.  It allows us to check, e.g. Column A + Column B <= Column C for all rows. 

But what if Column B has missing data, should the check fail, or be ignored?

Jeff has said that in all our uses of these custom-constraints presently, the check should just be ignored.  This PR implements this by catching the "NameNotFound" error that is thrown by the simple_eval function.

2020-11-25 13:20 UTC, jonathansberry commented on ckanext/validation/custom_checks.py
> +            return []
These are the two lines that ammend the checks behaviour

2020-11-25 13:27 UTC, tomeksabala requested changes
Why did you decide to go with simpleeval library?
Also it's not added in any requirements files in our ADR stack. Or at least I haven't found it yet.

Also I think it'd be really good to have some tests for that.

2020-11-25 16:51 UTC, jonathansberry commented
This is not my code.  I've just copied it over from goodtables-py.  SimpleEval is already installed because goodtables-py is installed.  Agreed, it's probably good practise to add to our requirements as well.  But the change looks like it is bigger than it is - I'm just ammending the behaviour of this file:
https://github.com/SrividhyaGuru/goodtables-py/blob/master/goodtables/contrib/checks/custom_constraint.py

2020-11-26 08:59 UTC, jonathansberry commented on ckanext/validation/tests/conftest.py
> +def log():
This fixture is copied from upstream good tables

2020-11-26 09:00 UTC, jonathansberry commented on ckanext/validation/tests/test_custom_checks.py
> +def test_check_custom_constraint(log):
These tests are copied and tweaked from upstream goodtables.  They should be run with pytest, explicitly specifying the test_custom_checks module.

2020-11-26 09:00 UTC, jonathansberry commented on test.ini
> +use = config:../ckan/test-core.ini
No previous configuration of the validation tests has taken place, this is a required change to run any tests for validation at all.

2020-11-26 09:01 UTC, tomeksabala approved these changes

2020-11-26 09:02 UTC, merged